# Generated by Django 5.2.4 on 2025-08-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_pereval_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coords',
            old_name='Longitude',
            new_name='longitude',
        ),
    ]
